@startuml Sign-in
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/aws-orange-light/puml-theme-aws-orange-light.puml


title Sign-in
note over Client
Web SSH Client with pre-configured settings
(ssh server)
end note
activate Client
activate Server
Client->Server: client key exchange init
Server->Client: server key exchange init
Client->Client: match encryption and hashing with server
Client<->Server: Diffie-Hellman Key exchange

Client->Enclave: request enclave 
note over Enclave
Enclave requested from Home ORK
end note

activate Enclave
Enclave->Enclave: sign-in
Enclave->Enclave: validate


alt sign && valid ?
    Enclave->Client:userid, cvk.pub, signature
    else
    Enclave->Client:401()
    deactivate Enclave
end

Client->Server: ssh-userauth (userid, cvk.pub, signature)
Server->Server: Compare received keys for authority
Server->Client: userauth success
deactivate Server


deactivate Client
@enduml