@startuml admin-signup
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/aws-orange-light/puml-theme-aws-orange-light.puml


title Admin Sign-up
note over Client
Web SSH Client
end note
activate Client
Client->TideButton: Press Buttton
activate TideButton

note over TideButton, Enclave
Enclave requested from Home ORK
end note
TideButton->Enclave: request enclave 
deactivate TideButton

activate Enclave
Enclave->Enclave: sign-up

alt existing user == yes?
    Enclave->Enclave: sign-in flow
    else
    Enclave->Enclave: sign-up flow
end
Enclave->Enclave: create userid and new cvk/ssh key
note over Enclave
    userid = hash(gUserCMK) for first 32 bytes
end note
Enclave->Enclave: validate

alt sign && valid ?
    Enclave->Client:cvk.pub, userid
    else
    Enclave->Client:401()
end
deactivate Enclave

deactivate Client
@enduml