@startuml Sign-in
title Sign-in
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/aws-orange-light/puml-theme-aws-orange-light.puml

participant "SSH \nServer" as Server
box "webSocket" #LightGray
participant "SSH \nProxy" as Proxy
participant "SSH \nClient" as Client
end box
participant "Enclave" as Enclave
collections "Tide \nNetwork" as Tide

group Pre-configured
note over Server
    gCVK : Public User key
end note

note over Client
    gVVK : Public SSH Server key
    sURL : SSH Proxy URL signed by VVK
end note

note over Tide
    userID : User ID
    VUID : User ID
    CVK : User Vendor key
end note
end group

activate Client
Client-[#Gray]>Proxy : connect
activate Proxy
Client<-Proxy : getInfo

note over Client
    User presses button
end note

Client->Enclave: OpenEnclave(gVVK, sURL)
activate Enclave

note over Enclave
    validate sURL ?
    Tide Login
end note

Enclave<->Tide: PRISM auth
Client<-Enclave: VUID, gCVK
Client->Proxy: Username(VUID), \nPublic(gCVK)

Proxy<-[#Gray]>Server: SSH Diffie-Hellman Key exchange
activate Server

note over Proxy
    Prep challenge
end note

Client<-Proxy: getSignature
Client->Enclave: challenge

Enclave->Tide: signSSH(challenge)

activate Tide
note over Tide
    Validate challenge
    Sign challenge
end note

Enclave<-Tide: signature
deactivate Tide

Enclave->Client: tideJWT, signature

deactivate Enclave

Client->Proxy: ReturnedSignature
Proxy-[#Gray]>Server: ssh-userauth (userid, gCVK, signature)
Server-[#Gray]>Server: Verify signature against gCVK
Server<-[#Gray]>Proxy: Commence session
Client<-[#Gray]>Proxy: Commence session
deactivate Server


deactivate Client
@enduml